### ISSUE TITLE
Problem seminar presentation

### ISSUE THREAD

**Issue by tohojo** [tohojo/RUC-math--crowd-modeling#3]
I figured I would move the discussion of the problem formulation page here, so that we can use the page itself for the contents, and have the discussion separately. I have cleaned up the page to reflect this and added a link to this discussion. :)

**Comment by tohojo** [comment]
Added first draft of slides. Latex source in the repo, and a pdf here: http://github.com/downloads/tohojo/RUC-math--crowd-modeling/problem-seminar.pdf :)

I'm thinking that if I do the problem formulation itself, the exemplarity and the our approach slides, you (Troels) can do the rest (i.e. the introduction and the "things we are not going to do"). How does that sound?

**Comment by slowmotionTRO** [comment]
That sounds fine

**Comment by slowmotionTRO** [comment]
Sow I'll do the first four slides and the last one...  right
